In [4]:
#A="elefante"
#A="a"
#A=1
#A=1.2
print(A)

1


In [13]:

for i in range(0,10):
    if (i<5):
        print(i)

IndentationError: expected an indented block (<ipython-input-13-ff5cb073b2a7>, line 2)

In [14]:
import numpy as np

In [26]:
data_first = np.loadtxt('/home/marco/Desktop/Assignment_2_first.txt') 

[[ 1.        0.74941 ]
 [ 2.        0.550438]
 [ 3.        0.443138]
 [ 4.        0.23135 ]
 [ 5.        0.217432]
 [ 6.        0.189725]
 [ 7.        0.423401]
 [ 8.        0.179381]
 [ 9.        0.431585]
 [10.        0.177888]
 [11.        0.185811]
 [12.        0.445935]
 [13.        0.439822]
 [14.        0.449893]
 [15.        0.186836]
 [16.        0.446562]
 [17.        0.439624]
 [18.        0.179087]
 [19.        0.442946]
 [20.        0.180747]
 [ 1.        0.749316]
 [ 2.        0.392256]
 [ 3.        0.289092]
 [ 4.        0.452383]
 [ 5.        0.217607]
 [ 6.        0.442731]
 [ 7.        0.197998]
 [ 8.        0.179979]
 [ 9.        0.434926]
 [10.        0.44505 ]
 [11.        0.435735]
 [12.        0.177623]
 [13.        0.439418]
 [14.        0.452348]
 [15.        0.185841]
 [16.        0.448976]
 [17.        0.186257]
 [18.        0.179402]
 [19.        0.445502]
 [20.        0.459119]
 [ 1.        0.749701]
 [ 2.        0.392288]
 [ 3.        0.445215]
 [ 4.      

In [17]:
finale_first=np.zeros((20,2))

In [21]:
print(finale_first)

[[1.      0.74941]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]]


In [19]:
finale_first[0,0]=data[0,0]
finale_first[0,1]=data[0,1]
#print(finale_first)
for j in range(0,20):
    for i in range(1, int(len())
        finale_first[j,1]=finale_first[j,1]+data[j+i*j,1]

[[1.      0.74941]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]
 [0.      0.     ]]


In [29]:
data_temp=np.zeros((20,2))
for i in range(20):
    for n in range(0,int(len(data_first)/20)):
        data_first[i,1] = data_first[i,1] + data_first[i+n*20,1]
        #print(data_first)
    #data_all[i,1] = data_all[i,1]/(len(data_all)/20)
    data_temp[i,1] = data_first[i,1]/(int(len(data_first)/20+1))
    data_temp[i,0] = data_first[i,0]
data_first=data_temp 
data_temp=np.zeros((20,2))

In [30]:
print(data_first)

[[ 1.          2.14956467]
 [ 2.          1.38605387]
 [ 3.          1.08587753]
 [ 4.          0.97583733]
 [ 5.          0.94433487]
 [ 6.          0.95415353]
 [ 7.          0.80811073]
 [ 8.          0.88540033]
 [ 9.          0.94962973]
 [10.          0.7754628 ]
 [11.          1.0769678 ]
 [12.          0.7941812 ]
 [13.          0.95090287]
 [14.          1.01810407]
 [15.          0.83934953]
 [16.          0.9612882 ]
 [17.          1.01380247]
 [18.          0.78909133]
 [19.          0.91295013]
 [20.          1.0682516 ]]


In [ ]:
function (a,b):
bla bla
return(k)